services:
  my_notes_db:
    image: postgres:latest
    container_name: my_notes_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes/postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
    depends_on:
      - my_notes_db
    ports:
      - "8000:8000"

volumes:
  postgres_db:
